# Setup
title:               Oleg Shimchik
tagline:             'Random thoughts'
description:         'A blog about stuff'
url:                 https://shimchik.net
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Oleg Shimchik
  url:               https://shimchik.net
  email:             oleg@shimchik.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
